project:
  type: book

book:
  title: "Rkurssi"
  author: "Norah Jones"
  date: "13.5.2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - testilataus.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

